import type { NextPage } from 'next'
import Head from 'next/head'
import NextJsCarousel from '../modules/carousel/index'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NextJsCarousel />
        <h2>Perfumes are made when a carefully created blend of essential scented oils are mixed in solvents – typically alcohol and water. The life cycle of a fragrance is three-timed (think of it as a disappearing pyramid of notes), starting with the top, moving onto the heart, and finally settling with the base notes. </h2>
      </main>


    </div>
  )
}

export default Home
